services:
  mysql:
    image: mysql:9.3.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: items
      MYSQL_USER: fastapi_app
      MYSQL_PASSWORD: thisispassword
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    restart: always
    ports: 
      - 9090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    environment:
      DATABASE_HOST: mysql:3306
      DATABASE_USER: fastapi_app
      DATABASE_PASSWORD: thisispassword
      DATABASE_NAME: items
    depends_on:
      - mysql
    develop:
      watch:
        - action: rebuild
          path: /app
          target: /usr/src/app
